datasource:
 cookbook:
  pool-name: cookbook
  jdbc-url: jdbc:postgresql://localhost:5533/cookbook
  username: cookbook
  password: pibu
  driver-class-name: org.postgresql.Driver
spring:
 flyway:
  enabled: true
  #For tests
  locations: classpath:/db/test_migration
  schemas: COOKBOOK
 jpa:
  properties:
   active: prod
   hibernate:
    default_schema: COOKBOOK

